bank/urls.py
from django.conf.urls import url

from . import views

app_name='bank'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^homepage/$', views.homepage, name='homepage'),
    url(r'^view_accounts/$', views.view_accounts, name='view_accounts'),
    url(r'^money_transfer/$', views.money_transfer, name='money_transfer'),
    url(r'^sign_out/$', views.sign_out, name='sign_out'),
]

sampler/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^bank/', include('bank.urls')),
    url(r'^admin/', admin.site.urls),
]

bank/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Accounts(models.Model):
    # This line is required. Links Accounts to a UserProfile model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # The additional attributes we wish to include.
    balance = models.DecimalField(decimal_places=2, max_digits=20)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username

bank/forms.py
from django import forms
from models import Accounts
from django.utils.translation import ugettext as _
from django.contrib.auth import hashers
from django.contrib.auth.password_validation import validate_password
from sampler.settings import AUTH_PASSWORD_VALIDATORS
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean_username(self):
        data=self.cleaned_data['username']
        user_exists = User.objects.filter(username=data).exists()
        if not user_exists:
            raise forms.ValidationError(_('Check User Name and Password'), code='invalid')
        return data

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")
        if username and password:
            user_profile = User.objects.get(username=username)
            if not username or not password or not hashers.check_password(password, user_profile.password):
                raise forms.ValidationError(_('Check User Name and Password'), code='invalid')

class RegisterForm(forms.Form):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    username = forms.CharField(max_length=100)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean_email(self):
        data=self.cleaned_data['email']
        user_exists = User.objects.filter(email=data).exists()
        if user_exists:
            raise forms.ValidationError(_('Email already exists'), code='invalid')
        return data

    def clean_username(self):
        data=self.cleaned_data['username']
        user_exists = User.objects.filter(username=data).exists()
        if user_exists:
            raise forms.ValidationError(_('User Name already exists'), code='invalid')
        return data

    def clean_password(self):
        data=self.cleaned_data['password']
        """
        Add validation rules for password.
        ie.
        1. Length of 8 or more
        2. Must have letters + numbers
        3. ...
        """
        validate_password(password=data)
        return data

class MoneyTransferForm(forms.Form):
    to_email = forms.EmailField()
    transfer_value = forms.DecimalField(min_value=0, localize=True, decimal_places=2)
    from_email = forms.EmailField(widget=forms.HiddenInput())

    def clean_from_email(self):
        data = self.cleaned_data['from_email']
        user_exists = User.objects.filter(email=data).exists()
        if not user_exists:
            raise forms.ValidationError(_('Invalid email'), code='invalid')
        return data

    def clean_to_email(self):
        data = self.cleaned_data['to_email']
        user_exists = User.objects.filter(email=data).exists()
        if not user_exists:
            raise forms.ValidationError(_('Invalid email'), code='invalid')
        return data

    def clean(self):
        cleaned_data = super(MoneyTransferForm, self).clean()
        from_email = cleaned_data.get("from_email")
        transfer_value = cleaned_data.get("transfer_value")
        if from_email and transfer_value:
            user_account = Accounts.objects.get(user__email=from_email)
            if not user_account.balance >= transfer_value:
                raise forms.ValidationError(_('Insufficient Balance'), code='invalid')

bank/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from collections import namedtuple
from django.db import transaction
from django.contrib.auth import hashers, authenticate, login, logout
from django.contrib.auth.models import User

# Create your views here.
from django.http import HttpResponseRedirect

from .forms import RegisterForm, LoginForm, MoneyTransferForm
from .models import Accounts
from django.forms import ValidationError
from django.contrib.auth.decorators import login_required
from sampler.settings import LOGIN_URL


def index(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            #validate form
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            #hash password before looking up in database against stored hashed password

            user_profile = get_object_or_404(User, username=username)
            #if 404 then display some error message while reloading loginpage (index)
            user = authenticate(username=username, password=password)
            # import pdb; pdb.set_trace()
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('bank:homepage')
            else:
                form.add_error(None, ValidationError(_('Please check your log in credentials'), code='invalid'))
    else:
        form = LoginForm()
    return render(request=request, template_name='bank/index.html', context={'form': form})


def register(request):
    # display_info = namedtuple('display_info', ['display_name', 'field_name', 'input_type'])
    # display_infos = (
    #     display_info('User Name', 'username', 'text'),
    #     display_info('First Name', 'firstname', 'text'),
    #     display_info('Last Name', 'lastname', 'text'),
    #     display_info('Email', 'email', 'text'),
    #     display_info('Password', 'password', 'password'))
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            #create DB instance for user
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password'] #remember to hash both email and password for storing.. this is just test
            user_profile = User.objects.create_user(
                first_name=first_name,
                last_name=last_name,
                username=username,
                email=email,
                password=password)
            #import pdb; pdb.set_trace()
            user_profile.save()
            account = Accounts(user=user_profile, balance=100) #instantiate user Account with 100$
            account.save()
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('bank:homepage')
    else:
        form = RegisterForm()

    return render(request=request, template_name='bank/register.html', context={'form': form})


@login_required(login_url=LOGIN_URL)
def homepage(request):
    user_account = get_object_or_404(Accounts, user=request.user)
    user_profile = user_account.user
    return render(request=request, template_name='bank/homepage.html',
                  context={'user_profile': user_profile, 'user_account': user_account})


@login_required(login_url=LOGIN_URL)
def view_accounts(request):
    accounts = Accounts.objects.exclude(user=request.user)
    return render(request=request, template_name='bank/accounts.html',
                  context={'accounts': accounts})


@login_required(login_url=LOGIN_URL)
def money_transfer(request):
    user_account = get_object_or_404(Accounts, user=request.user)
    if request.method == 'POST':
        form = MoneyTransferForm(request.POST)
        with transaction.atomic():
            if form.is_valid():
                transfer_value = form.cleaned_data['transfer_value']
                recipient_email = form.cleaned_data['to_email']
                user_account.balance -= transfer_value
                user_account.save()
                recipient_account = Accounts.objects.get(user__email=recipient_email)
                recipient_account.balance += transfer_value
                recipient_account.save()
                return redirect('bank:homepage')
    else:
        form = MoneyTransferForm()

    return render(request=request, template_name='bank/transfer.html', context={'form': form, 'email': user_account.user.email})


def sign_out(request):
    logout(request)
    return redirect('bank:index')

bank/templates/bank/accounts.html
{% load bank_templatetags %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'bank/style.css' %}" />
<ul>
    <li><a href="{% url 'bank:homepage' %}">Home</a></li>
    <li><a class="active" href="{% url 'bank:view_accounts' %}">View All Accounts</a></li>
    <li><a href="{% url 'bank:money_transfer' %}">Transfer Money</a></li>
    <li style="float:right"><a href="{% url 'bank:sign_out' %}">Sign Out</a></li>
</ul>

<div id="main">
    <table>
        <tr>
            <th>Email</th>
            <th>Balance</th>
        </tr>
        {% for account in accounts %}
        <tr>
            <td id="user_info">{{account.user.email}}</td>
            <td id="user_info">{{account.balance|prepend_dollars}}</td>
        </tr>
        {% endfor %}
    </table>
</div>

bank/templates/bank/homepage.html
{% load bank_templatetags %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'bank/style.css' %}"/>
<ul>
    <li><a class="active" href="{% url 'bank:homepage' %}">Home</a></li>
    <li><a href="{% url 'bank:view_accounts' %}">View All Accounts</a></li>
    <li><a href="{% url 'bank:money_transfer' %}">Transfer Money</a></li>
    <li style="float:right"><a href="{% url 'bank:sign_out' %}">Sign Out</a></li>
</ul>

<div id="main">
    <div id="user_info">
        <span>First Name:</span>
        <span>{{user_profile.first_name}}</span>
    </div>
    <div id="user_info">
        <span>Last Name:</span>
        <span>{{user_profile.last_name}}</span>
    </div>
    <div id="user_info">
        <span>Username:</span>
        <span>{{user_profile.username}}</span>
    </div>
    <div id="user_info">
        <span>Email:</span>
        <span>{{user_profile.email}}</span>
    </div>
    <div id="user_info">
        <span>Account Balance:</span>
        <span>{{user_account.balance|prepend_dollars}}</span>
    </div>
</div>

bank/templates/bank/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'bank/style.css' %}"/>
<ul>
    <li><a class="active" href="{% url 'bank:index' %}">Log In</a></li>
    <li><a href="{% url 'bank:register' %}">Register</a></li>
</ul>
<h1>Simple Banking System</h1>
<div id="main">
    <form action="{% url 'bank:index' %}" method="post">
        {% csrf_token %}

        <div class="fieldWrapper">
            <label for="{{ form.username.id_for_label }}">Username:</label>
            {{ form.username }}
            {{ form.username.errors }}
        </div>
        <div class="fieldWrapper">
            <label for="{{ form.password.id_for_label }}">Password:</label>
            {{ form.password }}
            {{ form.password.errors }}
        </div>
        {{ form.non_field_errors }}

        <input type="submit" value="Log In"/>
    </form>

    <a href="{% url 'bank:register' %}">Sign Up</a>

</div>

bank/templates/bank/register.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'bank/style.css' %}" />
<ul>
    <li><a href="{% url 'bank:index' %}">Log In</a></li>
    <li><a  class="active" href="{% url 'bank:register' %}">Register</a></li>
</ul>
<h1>Simple Banking System</h1>
<div id="main">
    <form action="{% url 'bank:register' %}" method="post">
        {% csrf_token %}

        <div class="fieldWrapper">
            <label for="{{ form.first_name.id_for_label }}">First Name:</label>
            {{ form.first_name }}
            {{ form.first_name.errors }}
        </div>
        <div class="fieldWrapper">
            <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
            {{ form.last_name }}
            {{ form.last_name.errors }}
        </div>
        <div class="fieldWrapper">
            <label for="{{ form.username.id_for_label }}">Username:</label>
            {{ form.username }}
            {{ form.username.errors }}
        </div>
        <div class="fieldWrapper">
            <label for="{{ form.email.id_for_label }}">Email:</label>
            {{ form.email }}
            {{ form.email.errors }}
        </div>
        <div class="fieldWrapper">
            <label for="{{ form.password.id_for_label }}">Password:</label>
            {{ form.password }}
            {{ form.password.errors }}
        </div>
        {{ form.non_field_errors }}

        <input type="submit" value="Register" />
    </form>
</div>

bank/templates/bank/transfer.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'bank/style.css' %}" />
<ul>
    <li><a href="{% url 'bank:homepage' %}">Home</a></li>
    <li><a href="{% url 'bank:view_accounts' %}">View All Accounts</a></li>
    <li><a class="active" href="{% url 'bank:money_transfer' %}">Transfer Money</a></li>
    <li style="float:right"><a href="{% url 'bank:sign_out' %}">Sign Out</a></li>
</ul>
<div id="main">
    <form action="{% url 'bank:money_transfer' %}" method="post">
        {% csrf_token %}

        <div class="fieldWrapper">
            <label for="{{ form.to_email.id_for_label }}">Recipient Email:</label>
            {{ form.to_email }}
            {{ form.to_email.errors }}
        </div>
        <div class="fieldWrapper">
            <label for="{{ form.transfer_value.id_for_label }}">Transfer Amount:</label>
            {{ form.transfer_value }}
            {{ form.transfer_value.errors }}
        </div>
        {{ form.non_field_errors }}

        <input type="hidden" name="from_email" value="{{email}}" />

        <input type="submit" value="Send Money"/>
    </form>
</div>